backend:
  name: github
  repo: richTheCreator/ML-Spellbook-CMS
  branch: master # Branch to update (optional; defaults to master)
media_folder: "docs/.vuepress/public/images/"
public_folder: "images/"
publish_mode: editorial_workflow
collections:
  - name: "root" # Used in routes, e.g., /admin/collections/blog
    label: "Root" # Used in the UI
    folder: "docs/root" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "atoms" # Used in routes, e.g., /admin/collections/blog
    label: "Atoms" # Used in the UI
    folder: "docs/atoms" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
